ARCHIVE_THRESHOLD = 61
WEATHER_DB_FILE = f"weather-{LOCATION}-mqtt_data.db"
SCENE_DB_FILE = mqtt_commands.db
SUPERVISED_DIRECTORY = /home/auto/automation
WEB_DIRECTORY = /home/auto/web
WEB_STATUC_DIRECTORY = /home/auto/webstatic
HTML_DIRECTORY = /var/www/html
INDEX_TEMPLATE_FILE = f"{WEB_DIRECTORY}/index.html"
LOCAL_BROKER_HOST = localhost
LOCAL_BROKER_PORT = 1883
LOG_FILE = f'/home/auto/{SCRIPT_NAME}.log'
MAGICHOME_TOPIC = light/magic
MQTT_BROKER_HOST = localhost
MQTT_BROKER_PORT = 1883
WEATHER_TOPIC = environment/weather
WEATHER_UPDATE_SOCKET = /tmp/weather_update_socket
VALVE_TOPIC = water/valve
VALVE_CONTROL_URL = http://192.168.10.105/
VALVE_GPIO = 2
SCREENPOWER_TOPIC = screen/power
SCREENREDSHIFT_TOPIC = screen/redshift
SERVER_HA_HOST = ha
SERVER_HA_PORT = 1883
TOPIC_IN_FROM_WEB = in
TOPIC_OUT_TO_WEB = out
ENVIRONMENT_TOPIC_PREFIX = environment/temperature
ENVIRONMENT_DATA_FILE = f"temperature-{location}-mqtt_data.db"
ENVIRONMENT_DATA_ARCHIVE = f"temperature-{location}-mqtt_archive.db"
DIRECTORY_TO_WATCH = /home/auto/web
INDEX_HTML_FILE = /var/www/html/index.html
INDEX_TEMPLATE_FILE = /home/auto/web/index.html
NETWORK_TOPIC_PREFIX = network
NETWORK_DATA_FILE = network-{location}-mqtt_data.db
NETWORK_DATA_ARCHIVE = network-{location}-mqtt_archive.db
NETWORK_DATA_FILE2 = network-{location}-mqtt_data2.db
NETWORK_DATA_ARCHIVE2 = network-{location}-mqtt_archive2.db
TOPIC_OUT_TO_WEB2 = out2
TREADMILL_TOPIC = ftms/treadmill
TREADMILL_DB_FILE = treadmill-mqtt_data.db
TREADMILL_DB_ARCHIVE = treadmill-mqtt_archive.db
TREADMILL_ADDRESS = 18:7A:9A:C6:35:2F

